insert into tb_colaborador (registro, nome, email, status, senha, cargo) values ('9002065', 'LUCAS RODRIGUES', 'LUCAS.RODRIGUES@TESTE.COM', 'ATIVO', '1234', 'DEV');
insert into tb_colaborador (registro, nome, email, status, senha, cargo) values ('9001010', 'ROGERIO ALVES', 'ROGERIO.ALVES@TESTE.COM', 'ATIVO', '1010', 'PLANEJADOR');
insert into tb_colaborador (registro, nome, email, status, senha, cargo) values ('9002020', 'JOAO SILVEIRA', 'JOAO.SILVEIRA@TESTE.COM', 'ATIVO', '2020', 'ENCARREGADO');
insert into tb_colaborador (registro, nome, email, status, senha, cargo) values ('9003030', 'JUCA DA CUNHA', 'JUCA.CUNHA@TESTE.COM', 'ATIVO', '3030', 'OPERADOR');


insert into tb_partnumber (codigo, descricao, status) values ('9379437', 'FAROL 1', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('0686398', 'FAROL 2', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('0191385', 'FAROL 3', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('5274189', 'FAROL 4', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('2368978', 'FAROL 5', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('4207842', 'FAROL 6', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('6697110', 'FAROL 7', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('7593260', 'FAROL 8', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('3654367', 'FAROL 9', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('9969900', 'FAROL 10', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('8529421', 'FAROL 11', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('9668492', 'FAROL 12', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('0628452', 'FAROL 13', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('1766822', 'FAROL 14', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('7004760', 'FAROL 15', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('3065061', 'FAROL 16', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('6021886', 'FAROL 17', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('1145567', 'FAROL 18', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('1784001', 'FAROL 19', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('9950084', 'FAROL 20', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('4548956', 'FAROL 21', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('4299217', 'FAROL 22', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('7148367', 'FAROL 23', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('4311767', 'FAROL 24', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('2609680', 'FAROL 25', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('6374954', 'FAROL 26', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('8547444', 'FAROL 27', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('0350209', 'FAROL 28', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('3830264', 'FAROL 29', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('2482759', 'FAROL 30', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('1326160', 'FAROL 31', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('6923259', 'FAROL 32', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('7475765', 'FAROL 33', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('6273223', 'FAROL 34', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('8136310', 'FAROL 35', 'ATIVO');
insert into tb_partnumber (codigo, descricao, status) values ('5186336', 'FAROL 36', 'ATIVO');



insert into tb_pecas (cod_peca, descricao, status) values ('36278', 'ITEM 1', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('53777', 'ITEM 2', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('45349', 'ITEM 3', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('33406', 'ITEM 4', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('89536', 'ITEM 5', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('97921', 'ITEM 6', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('25264', 'ITEM 7', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('24601', 'ITEM 8', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('15218', 'ITEM 9', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('31471', 'ITEM 10', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('21563', 'ITEM 11', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('97122', 'ITEM 12', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('96603', 'ITEM 13', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('80953', 'ITEM 14', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('12641', 'ITEM 15', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('78901', 'ITEM 16', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('16595', 'ITEM 17', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('85939', 'ITEM 18', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('65881', 'ITEM 19', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('10626', 'ITEM 20', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('52665', 'ITEM 21', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('62437', 'ITEM 22', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('22897', 'ITEM 23', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('18272', 'ITEM 24', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('58495', 'ITEM 25', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('48940', 'ITEM 26', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('74010', 'ITEM 27', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('48627', 'ITEM 28', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('16880', 'ITEM 29', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('95834', 'ITEM 30', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('76612', 'ITEM 31', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('52953', 'ITEM 32', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('15492', 'ITEM 33', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('65918', 'ITEM 34', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('72922', 'ITEM 35', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('92629', 'ITEM 36', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('14631', 'ITEM 37', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('14538', 'ITEM 38', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('80196', 'ITEM 39', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('79173', 'ITEM 40', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('02472', 'ITEM 41', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('03099', 'ITEM 42', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('13138', 'ITEM 43', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('77097', 'ITEM 44', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('97323', 'ITEM 45', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('54474', 'ITEM 46', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('99382', 'ITEM 47', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('01972', 'ITEM 48', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('00437', 'ITEM 49', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('49093', 'ITEM 50', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('61637', 'ITEM 51', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('22486', 'ITEM 52', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('89786', 'ITEM 53', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('79956', 'ITEM 54', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('52095', 'ITEM 55', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('10288', 'ITEM 56', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('80504', 'ITEM 57', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('58561', 'ITEM 58', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('87364', 'ITEM 59', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('05888', 'ITEM 60', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('66233', 'ITEM 61', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('44066', 'ITEM 62', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('44765', 'ITEM 63', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('87034', 'ITEM 64', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('61542', 'ITEM 65', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('86519', 'ITEM 66', 'ATIVO');
insert into tb_pecas (cod_peca, descricao, status) values ('41730', 'ITEM 67', 'ATIVO');

insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 9, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 3, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 40, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 15, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 55, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (1, 49, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 1, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 51, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 19, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 13, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 2, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 16, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (2, 8, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (3, 8, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (3, 40, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (3, 14, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (3, 6, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 12, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 18, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 36, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 67, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 54, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 30, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 3, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 50, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 5, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 36, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (4, 10, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 52, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 56, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 43, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 14, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 30, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (5, 52, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 32, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 53, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 28, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 67, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 2, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 15, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (6, 24, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (7, 55, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (7, 58, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (7, 33, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (7, 50, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (7, 9, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (8, 36, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (8, 55, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (8, 47, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 8, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 42, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 45, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 57, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 6, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 8, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (9, 6, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 64, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 29, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 27, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 14, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 52, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 48, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 23, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 65, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (10, 50, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 32, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 10, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 53, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 62, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 11, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 32, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 60, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 51, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 36, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 34, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 13, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (11, 11, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 61, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 13, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 24, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 10, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 18, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 48, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 52, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 41, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 40, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 22, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 16, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 37, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (12, 43, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 4, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 66, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 33, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 14, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 44, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (13, 29, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (14, 51, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (14, 18, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (14, 27, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 29, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 49, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 48, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 43, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 56, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 5, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (15, 25, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 10, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 45, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 46, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 44, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 7, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 60, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 42, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 19, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 43, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 43, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (16, 56, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 28, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 10, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 60, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 62, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 25, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 44, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 3, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 5, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 7, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 34, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (17, 66, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 32, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 19, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 60, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 25, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 43, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 19, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 3, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 45, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 45, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 23, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 15, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 22, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 52, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 12, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 49, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 63, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 31, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (18, 44, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 5, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 3, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 58, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 21, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 20, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 9, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 18, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 67, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 20, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 3, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 3, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 11, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 43, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (19, 26, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 39, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 43, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 9, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 17, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 11, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 41, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 65, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 6, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 15, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (20, 52, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 54, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 17, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 21, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 32, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 60, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 62, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 36, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 31, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (21, 66, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 52, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 30, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 64, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 38, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 31, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 7, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 30, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 36, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 39, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 65, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 43, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (22, 16, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 41, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 62, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 45, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 23, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 39, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 21, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 9, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 55, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (23, 44, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (24, 19, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (24, 29, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (24, 6, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (24, 19, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 27, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 44, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 18, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 35, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 36, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 20, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (25, 14, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 10, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 50, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 21, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 22, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 35, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 22, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 27, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 49, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 16, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 24, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 33, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 46, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 60, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 36, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 43, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 56, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (26, 61, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (27, 21, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (27, 2, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (27, 50, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (27, 35, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 13, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 63, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 58, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 34, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 38, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 34, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 56, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 16, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 67, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (28, 4, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 43, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 10, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 50, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 32, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 22, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 27, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (29, 59, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 32, 10);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 56, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 59, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 55, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 8, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 65, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (30, 18, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (31, 21, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (31, 44, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (31, 67, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (31, 22, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 33, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 27, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 29, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 48, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 59, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 52, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 56, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 62, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 10, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 66, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (32, 42, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 62, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 5, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 31, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 21, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 19, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 35, 6);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 56, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 27, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (33, 27, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (34, 29, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (34, 60, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (34, 52, 8);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (35, 2, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (35, 27, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (35, 49, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 61, 7);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 12, 5);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 42, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 17, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 28, 12);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 51, 11);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 64, 1);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 11, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 33, 14);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 8, 15);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 57, 3);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 59, 9);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 1, 2);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 10, 4);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 5, 13);
insert into tb_bom (partnumber_id, pecas_id, quantidade) values (36, 64, 2);


insert into tb_pedido (data_criacao, num_ordem, status, requisitante_registro) values ("2022-11-25 17:37:50.479745", "RQ10001", "EMITIDO", "9002065");

insert into tb_itenspedido (data_producao, hora_producao, quantidade, codigo_id, pedido_id) values ("2022-11-26", "10:00:00", 150, 18, 1);
insert into tb_itenspedido (data_producao, hora_producao, quantidade, codigo_id, pedido_id) values ("2022-11-26", "10:00:00", 200, 17, 1);
insert into tb_itenspedido (data_producao, hora_producao, quantidade, codigo_id, pedido_id) values ("2022-11-26", "10:00:00", 190, 4, 1);